name: Main Workflow

# trigger
on:
  push:
    branches:
      - main
      - dev

env:
  PORT: 3000

jobs:
  build:
    name: Build Laravel App
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0.25
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: password
          MYSQL_USERNAME: root
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          composer install

      - name: Setup Env
        run: |
          cp .env.ci .env
          cp .env.ci .env.testing

      - name: Build the Application
        run: |
          php artisan key:generate

      - name: Migrate
        run: |
          php artisan migrate

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: |
          php artisan test
