name: Main Workflow

# trigger
on:
  push:
    branches:
      - main
      - dev

env:
  PORT: 3000

jobs:
  build:
    name: Build Laravel App
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          composer install
      
      - name: Run MySQL container
        run: |
          docker run \
            --name my-mysql-container \
            -e MYSQL_ALLOW_EMPTY_PASSWORD=false \
            -e MYSQL_ROOT_PASSWORD=password \
            -e MYSQL_USER=root \
            -e MYSQL_DATABASE=test \
            -p 3306:3306 \
            mysql:8.0.25
          
          sleep 5

          docker ps
      
      - name: Wait for MySQL to start
        run: |
          sleep 5  # Increased wait time to ensure MySQL is fully started
      
      - name: List docker process
        run: |
           docker ps

      - name: Setup Env
        run: |
          cp .env.ci .env
          cp .env.ci .env.testing

      - name: Build the Application
        run: |
          php artisan key:generate

      - name: Migrate
        run: |
          php artisan migrate

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: |
          php artisan test
